[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.openssl", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.fileinfo"]

[phases.build]
cmds = [
  "mkdir -p uploads/tickets",
  "mkdir -p uploads/avatars", 
  "chmod -R 777 uploads/"
]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php" 